# Generated by Django 3.1.4 on 2021-12-05 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_auto_20211205_0357'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Account_exec',
            new_name='Account_executive',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='account_exec',
            new_name='account_executive',
        ),
    ]
