# Generated by Django 3.1.4 on 2021-12-09 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_auto_20211205_0400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='age',
            new_name='phone_number',
        ),
        migrations.AddField(
            model_name='lead',
            name='company',
            field=models.CharField(default='company', max_length=40),
        ),
        migrations.AddField(
            model_name='lead',
            name='industry',
            field=models.CharField(default='industry', max_length=30),
        ),
    ]
