# Generated by Django 3.1.4 on 2021-12-09 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_auto_20211208_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='company',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='lead',
            name='industry',
            field=models.CharField(default='', max_length=30),
        ),
    ]
